# @package _global_
dataset:
  view_sampler:
    name: bounded
    min_distance_between_context_views: 75 #45
    max_distance_between_context_views: 100 #192
    min_distance_to_context_views: 0
    warm_up_steps: 50_000
    initial_min_distance_between_context_views: 25 #25
    initial_max_distance_between_context_views: 50 #45
    num_target_views: 1
    num_context_views: 2
      